// app/page.tsx
import React from "react";
import type { Metadata } from "next";

import SearchForm from "@/components/search-form";
import { fetchAirports } from "@/lib/getData";
import SearchFormSkeleton from "@/components/search-form-skeleton";
import Navigation from "@/components/navigation";

export const metadata: Metadata = {
  title: "Flight Planner",
  description: "Generated by create next app",
};

export default async function Home() {
  const airports = await fetchAirports();

  return (
    <div className='min-h-screen bg-background'>
      <Navigation />
      <main className='container mx-auto px-4 py-8'>
        <div className='flex flex-col md:flex-row gap-8'>
          <div className='md:w-1/2 flex items-center'>
            <h1 className='text-4xl md:text-6xl font-bold leading-tight'>
              FLY SMART.
              <br />
              BOOK EASY.
              <br />
              TRAVEL HAPPY.
            </h1>
          </div>
          {airports ? (
            <SearchForm airports={airports} />
          ) : (
            <SearchFormSkeleton />
          )}
        </div>
      </main>
    </div>
  );
}
